#spring:
#  datasource:
#    username: root
#    password: Venkatesh
#    url: jdbc:mysql://localhost:3303/jwt
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3303/spring_jwt
    username: root
    password: Venkatesh
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


